# Generated by Django 5.1.3 on 2024-11-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.IntegerField(primary_key=True, serialize=False)),
                ('data_agenda', models.DateField(blank=True, null=True)),
                ('tipo_rc', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_cadastro', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('semanas_gestacao', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('scanner', models.CharField(blank=True, max_length=20, null=True)),
                ('data_coleta', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cadastro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coletista',
            fields=[
                ('nome', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'coletista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desvinculo',
            fields=[
                ('id_desvinculo', models.IntegerField(primary_key=True, serialize=False)),
                ('data_desvinculo', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'desvinculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('nome', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id_materiais', models.IntegerField(primary_key=True, serialize=False)),
                ('carteirinha', models.BooleanField(blank=True, null=True)),
                ('mordedor', models.BooleanField(blank=True, null=True)),
                ('gorro', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'materiais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recoleta',
            fields=[
                ('id_recoleta', models.IntegerField(primary_key=True, serialize=False)),
                ('scanner', models.CharField(blank=True, max_length=20, null=True)),
                ('data_recoleta', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recoleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsvel',
            fields=[
                ('id_responsavel', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome_responsavel', models.CharField(blank=True, max_length=45, null=True)),
                ('telefone_responsavel', models.IntegerField(blank=True, null=True)),
                ('endereco_cadastro', models.CharField(blank=True, max_length=45, null=True)),
                ('bairro_cadastro', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_atual', models.CharField(blank=True, max_length=45, null=True)),
                ('bairro_atual', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'responsável',
                'managed': False,
            },
        ),
    ]
