# Generated by Django 5.1.3 on 2025-02-28 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infantID_coleta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsvel',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
