# Generated by Django 5.1.3 on 2025-01-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infantID_coleta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='justificativa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
