# Generated by Django 5.1.3 on 2025-01-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infantID_coleta', '0002_cadastro_justificativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoleta',
            name='justificativa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='recoleta',
            name='n_dedos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
