# Generated by Django 5.1.3 on 2025-02-26 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infantID_coleta', '0003_recoleta_justificativa_recoleta_n_dedos'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_atualizado', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_atualizado', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade_atualizado', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro_atualizado', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_atualizado', models.CharField(blank=True, max_length=45, null=True)),
                ('pais_atualizado', models.CharField(blank=True, max_length=50, null=True)),
                ('cep_antigo', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_antigo', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade_antigo', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro_antigo', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_antigo', models.CharField(blank=True, max_length=45, null=True)),
                ('pais_antigo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_alteracao', models.DateField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(blank=True, db_column='responsavel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infantID_coleta.responsvel')),
            ],
            options={
                'db_table': 'historico_endereco',
            },
        ),
    ]
