# Generated by Django 5.1.3 on 2025-03-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infantID_coleta', '0003_cadastro_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='data_criacao',
        ),
    ]
