# Generated by Django 5.1.3 on 2025-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infantID_coleta', '0004_historicoendereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsvel',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='responsvel',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
