# Generated by Django 5.1.3 on 2025-02-27 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infantID_coleta', '0005_alter_responsvel_cidade_alter_responsvel_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_antigo', models.CharField(max_length=11)),
                ('telefone_atualizado', models.CharField(max_length=11)),
                ('reponsavel', models.ForeignKey(db_column='responsavel', on_delete=django.db.models.deletion.DO_NOTHING, to='infantID_coleta.responsvel')),
            ],
        ),
    ]
