# Generated by Django 5.1.3 on 2025-02-27 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infantID_coleta', '0006_historicotelefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicotelefone',
            name='reponsavel',
            field=models.ForeignKey(db_column='responsavel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infantID_coleta.responsvel'),
        ),
        migrations.AlterField(
            model_name='historicotelefone',
            name='telefone_antigo',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicotelefone',
            name='telefone_atualizado',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterModelTable(
            name='historicotelefone',
            table='historico_telefone',
        ),
    ]
