# Generated by Django 5.1.3 on 2025-02-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infantID_coleta', '0007_alter_historicotelefone_reponsavel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicotelefone',
            old_name='reponsavel',
            new_name='responsavel',
        ),
    ]
